/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ernkr
 */
import static java.lang.Integer.parseInt;
import javax.swing.ImageIcon;
public class GameFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameFrame.class.getName());
    private GameEngine gameEngine = new GameEngine();
    private int playerBet = 0;

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
    }
    public int getPlayerBet(){
        return playerBet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dealers_cards_panel = new javax.swing.JPanel();
        d_card_placement_label1 = new javax.swing.JLabel();
        d_card_placement_label2 = new javax.swing.JLabel();
        d_card_placement_label3 = new javax.swing.JLabel();
        d_card_placement_label4 = new javax.swing.JLabel();
        players_cards_panel = new javax.swing.JPanel();
        p_card_placement_label1 = new javax.swing.JLabel();
        p_card_placement_label2 = new javax.swing.JLabel();
        p_card_placement_label3 = new javax.swing.JLabel();
        p_card_placement_label4 = new javax.swing.JLabel();
        dealer_points_label = new javax.swing.JLabel();
        player_points_label = new javax.swing.JLabel();
        deck_label = new javax.swing.JLabel();
        buttons_panel = new javax.swing.JPanel();
        hit_button = new javax.swing.JButton();
        stand_button = new javax.swing.JButton();
        bet_panel = new javax.swing.JPanel();
        increase_button = new javax.swing.JButton();
        decrease_button = new javax.swing.JButton();
        bet_label = new javax.swing.JLabel();
        bet_button = new javax.swing.JButton();
        dollar_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blackjack");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("GameFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1050, 600));
        setSize(new java.awt.Dimension(1000, 670));

        dealers_cards_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dealers_cards_panel.setName("dealers_cards_panel"); // NOI18N

        d_card_placement_label1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        d_card_placement_label1.setPreferredSize(new java.awt.Dimension(127, 184));
        dealers_cards_panel.add(d_card_placement_label1);

        d_card_placement_label2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        d_card_placement_label2.setPreferredSize(new java.awt.Dimension(127, 184));
        dealers_cards_panel.add(d_card_placement_label2);

        d_card_placement_label3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        d_card_placement_label3.setPreferredSize(new java.awt.Dimension(127, 184));
        dealers_cards_panel.add(d_card_placement_label3);

        d_card_placement_label4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        d_card_placement_label4.setPreferredSize(new java.awt.Dimension(127, 184));
        dealers_cards_panel.add(d_card_placement_label4);

        players_cards_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        players_cards_panel.setName("players_cards_panel"); // NOI18N

        p_card_placement_label1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p_card_placement_label1.setPreferredSize(new java.awt.Dimension(127, 184));
        players_cards_panel.add(p_card_placement_label1);

        p_card_placement_label2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p_card_placement_label2.setPreferredSize(new java.awt.Dimension(127, 184));
        players_cards_panel.add(p_card_placement_label2);

        p_card_placement_label3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p_card_placement_label3.setPreferredSize(new java.awt.Dimension(127, 184));
        players_cards_panel.add(p_card_placement_label3);

        p_card_placement_label4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p_card_placement_label4.setPreferredSize(new java.awt.Dimension(127, 184));
        players_cards_panel.add(p_card_placement_label4);

        dealer_points_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dealer_points_label.setText("Dealer : 0");
        dealer_points_label.setName("dealer_points_label"); // NOI18N

        player_points_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player_points_label.setText("You : 0");
        player_points_label.setName("player_points_label"); // NOI18N

        deck_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/BACK.png"))); // NOI18N
        deck_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        deck_label.setName("deck_label"); // NOI18N

        buttons_panel.setName("buttons_panel"); // NOI18N

        hit_button.setText("Hit");
        hit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hit_buttonActionPerformed(evt);
            }
        });

        stand_button.setText("Stand");

        javax.swing.GroupLayout buttons_panelLayout = new javax.swing.GroupLayout(buttons_panel);
        buttons_panel.setLayout(buttons_panelLayout);
        buttons_panelLayout.setHorizontalGroup(
            buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttons_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hit_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stand_button, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttons_panelLayout.setVerticalGroup(
            buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttons_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hit_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stand_button)
                .addContainerGap())
        );

        increase_button.setText("+");
        increase_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increase_buttonActionPerformed(evt);
            }
        });

        decrease_button.setText("-");
        decrease_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrease_buttonActionPerformed(evt);
            }
        });

        bet_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bet_label.setText("0");

        bet_button.setText("Bet");
        bet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bet_buttonActionPerformed(evt);
            }
        });

        dollar_label.setText("$");

        javax.swing.GroupLayout bet_panelLayout = new javax.swing.GroupLayout(bet_panel);
        bet_panel.setLayout(bet_panelLayout);
        bet_panelLayout.setHorizontalGroup(
            bet_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bet_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bet_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(increase_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(decrease_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bet_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bet_panelLayout.createSequentialGroup()
                        .addComponent(bet_label, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dollar_label)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bet_panelLayout.setVerticalGroup(
            bet_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bet_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(increase_button)
                .addGap(18, 18, 18)
                .addGroup(bet_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bet_label)
                    .addComponent(dollar_label))
                .addGap(18, 18, 18)
                .addComponent(decrease_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bet_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deck_label)
                    .addComponent(bet_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(players_cards_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dealers_cards_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(player_points_label, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(312, 312, 312)))
                        .addComponent(buttons_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(dealer_points_label, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dealer_points_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dealers_cards_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deck_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttons_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(players_cards_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player_points_label))
                    .addComponent(bet_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hit_buttonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hit_buttonActionPerformed

    private void increase_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increase_buttonActionPerformed
            // TODO add your handling code here:
            Integer num = parseInt(bet_label.getText());
            num += 10;
            bet_label.setText(num.toString());
    }//GEN-LAST:event_increase_buttonActionPerformed

    private void decrease_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrease_buttonActionPerformed
        // TODO add your handling code here:
        Integer num = parseInt(bet_label.getText());
        if(num != 0){
            num -= 10;
            bet_label.setText(num.toString());
        }
    }//GEN-LAST:event_decrease_buttonActionPerformed

    private void bet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bet_buttonActionPerformed
        // TODO add your handling code here:
        Dealer dealer = gameEngine.getDealer();
        Player player = gameEngine.getPlayer();
        playerBet = parseInt(bet_label.getText());
        bet_label.setText("0");
        bet_panel.setVisible(false);
        player.bet();
        dealer.deal_cards(gameEngine.getDeck(), gameEngine.getPlayer());
        d_card_placement_label1.setIcon(CardIcons.getIcon(dealer.cards.getFirst()));
        d_card_placement_label2.setIcon(CardIcons.getIcon(dealer.cards.get(1)));
        p_card_placement_label1.setIcon(CardIcons.getIcon(player.cards.getFirst()));
        p_card_placement_label2.setIcon(CardIcons.getIcon(player.cards.get(1)));
        dealer_points_label.setText("Dealer :"+ValueCalculator.calculate(dealer.cards).toString());
        player_points_label.setText("You :"+ValueCalculator.calculate(player.cards).toString());
        player.set_turn();
    }//GEN-LAST:event_bet_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameFrame().setVisible(true));
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bet_button;
    private javax.swing.JLabel bet_label;
    private javax.swing.JPanel bet_panel;
    private javax.swing.JPanel buttons_panel;
    private javax.swing.JLabel d_card_placement_label1;
    private javax.swing.JLabel d_card_placement_label2;
    private javax.swing.JLabel d_card_placement_label3;
    private javax.swing.JLabel d_card_placement_label4;
    private javax.swing.JLabel dealer_points_label;
    private javax.swing.JPanel dealers_cards_panel;
    private javax.swing.JLabel deck_label;
    private javax.swing.JButton decrease_button;
    private javax.swing.JLabel dollar_label;
    private javax.swing.JButton hit_button;
    private javax.swing.JButton increase_button;
    private javax.swing.JLabel p_card_placement_label1;
    private javax.swing.JLabel p_card_placement_label2;
    private javax.swing.JLabel p_card_placement_label3;
    private javax.swing.JLabel p_card_placement_label4;
    private javax.swing.JLabel player_points_label;
    private javax.swing.JPanel players_cards_panel;
    private javax.swing.JButton stand_button;
    // End of variables declaration//GEN-END:variables
    
}
